### ISSUE TITLE
Compilation errors: "a template declaration cannot appear at block scope"

### ISSUE THREAD

**Issue by Fabian42** [kamui-fin/gazou#10]
I just tried to update to the latest version of the `gazou-git` package on Manjaro and got a lot of errors called "`a template declaration cannot appear at block scope`" and then a build failure. The full log is here: [log.txt](https://github.com/kamui-fin/gazou/files/7533837/log.txt)

**Comment by kamui-fin** [comment]
Looks like I made a mistake of putting that include inside of main. Fixed and updated the AUR package.

**Comment by Fabian42** [comment]
I'll check it out once the other package update is done that is for some reason running for over 2½ hours already. :D

**Comment by Fabian42** [comment]
It keeps updating to what it claims to be version 0.2.0-2, but afterwards it's version 0.2.0-1 again, so the update is in the list again and I can update again and so on.

**Comment by kamui-fin** [comment]
Does the upgrade loop still occur? I think it should be fixed now.

**Comment by Fabian42** [comment]
Ironic timing, now I have other upgrade problems. I'll reply once those are fixed and I can test this again.

**Comment by Fabian42** [comment]
Yes, it works now!
