### ISSUE TITLE
Fails with "tesseract" version 5

### ISSUE THREAD

**Issue by Fabian42** [kamui-fin/gazou#13]
When launching Gazou now, I get:

`gazou: error while loading shared libraries: libtesseract.so.4: cannot open shared object file: No such file or directory`

I have the package `tesseract` installed and `/usr/lib/libtesseract.so.5` exists, but not `libtesseract.so.4`.

I also cannot cheat by creating a symbolic link with the name it expects, because then I get this:

`gazou: symbol lookup error: gazou: undefined symbol: _ZN9tesseract11TessBaseAPI4InitEPKcS2_NS_13OcrEngineModeEPPciPK13GenericVectorI6STRINGESA_b`

**Comment by Fabian42** [comment]
I can work around it for now by building version 4 from source in another folder and symlinking that.

**Comment by kamui-fin** [comment]
I added version checks for pkgbuild, so it should be able to pick up any of those versions >= 4. Let me know if the issue still persists. Thanks!

**Comment by Fabian42** [comment]
Yes, confirmed fixed!
