### ISSUE TITLE
Enhancement: Pipe an image from stdin

### ISSUE THREAD

**Issue by wildwestrom** [kamui-fin/gazou#14]
Here's what I'd like to do.

```fish
grim -g (slurp) /dev/stdout | gazou -h -
```

I get the error `Invalid image path` when I try to do this.
I see the output of `stderror` on `grim` is `SIGPIPE` as well.

**Comment by notevenaperson** [comment]
This, or loading by filepath like `gazou text.png` would be nice. One might want to use Gazou's OCR by itself. Currently the only way to load text into Gazou is screenshoting it.

**Comment by kamui-fin** [comment]
> This, or loading by filepath like `gazou text.png` would be nice. One might want to use Gazou's OCR by itself. Currently the only way to load text into Gazou is screenshoting it.

You can load by filepath in the current version using the `gazou text.png` format.

**Comment by kamui-fin** [comment]
Implemented pipe functionality in version 0.3.0

**Comment by notevenaperson** [comment]
Thank you for the work.
