### ISSUE TITLE
GNOME 42/X11: Gazou Applet Settings Won't Open

### ISSUE THREAD

**Issue by LunaGNUisance** [kamui-fin/gazou#16]
In previous versions of GNOME, I was able to open the Gazou settings by double clicking the system tray icon. However, since upgrading to GNOME 42, I can no longer do this. I'm not sure when this behavior started happening, as I haven't used Gazou for several months.

I'm not sure if it's related, but calling `gazou -h` or `gazou -v` from the terminal and copying a section of text doesn't copy it to my clipboard, either. I only get this feedback, which doesn't seem to be an error:

```
requestActivate() called for  QWidgetWindow(0x55b0b387c9e0, name="SelectorWidgetClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
「汐汐ももう . :渦ろ ゃんこj!だから大聞きだょよっ 」'」
```

I built the AUR package an hour ago, so it should be up-to-date with the latest commit. I have all the dependencies listed for the package. I'm also definitely using x11 (output of `echo $XDG_SESSION_TYPE` is `x11`).

Here's a video of me attempting to open Gazou from the system tray by double-clicking and right-clicking it:

https://user-images.githubusercontent.com/78894455/163709628-47c09118-f20d-4880-a5ff-1c773dabee82.mp4

**Comment by kamui-fin** [comment]
Hey, I just tested it with on Gnome 44 on Fedora Workstation 38. I pushed a feature to show a "Configure" menu item when you click the tray icon, and it should now open the window properly. Try the new version and it should work now, assuming you're using [this](https://extensions.gnome.org/extension/615/appindicator-support/) GNOME tray extension.
