### ISSUE TITLE
How to use gazou

### ISSUE THREAD

**Issue by panjutorials** [kamui-fin/gazou#18]
Hi guys. How can I actually use gazou?
I've started the exe on windows and pressed alt+d then mark my Japanese text. So what's next? 
It doesn't seem to be stored in the clipboard and as it doesn't have a GUI I have no way of seeing the text that was recognized.
Thanks in advance

**Comment by Fabian42** [comment]
It should be in the clipboard. If it isn't, that's a bug. Or it didn't recognise anything, which would be bad, too.

**Comment by kamui-fin** [comment]
Just created a new windows release with all the newest commits. Tested on a fresh system and works as expected.
