### ISSUE TITLE
Fails To Build on Arch due to leptonica 

### ISSUE THREAD

**Issue by Cryptoniac1** [kamui-fin/gazou#19]
When running the build on arch right after an update the following errors are viewed
`/home/user/builds/gazou/src/ocr.cpp: In constructor ‘OCR::OCR()’:
/home/user/builds/gazou/src/ocr.cpp:16:21: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   16 |     corrections = {{"〈", "く"}, {"<", "く"}, {"＜", "く"}, {"L", "し"},
      |                     ^~~~
/home/user/builds/gazou/src/ocr.cpp:16:27: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   16 |     corrections = {{"〈", "く"}, {"<", "く"}, {"＜", "く"}, {"L", "し"},
      |                           ^~~~
/home/user/builds/gazou/src/ocr.cpp:16:35: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   16 |     corrections = {{"〈", "く"}, {"<", "く"}, {"＜", "く"}, {"L", "し"},
      |                                   ^~~
/home/user/builds/gazou/src/ocr.cpp:16:40: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   16 |     corrections = {{"〈", "く"}, {"<", "く"}, {"＜", "く"}, {"L", "し"},
      |                                        ^~~~
/home/user/builds/gazou/src/ocr.cpp:16:48: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   16 |     corrections = {{"〈", "く"}, {"<", "く"}, {"＜", "く"}, {"L", "し"},
      |                                                ^~~~
/home/user/builds/gazou/src/ocr.cpp:16:54: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   16 |     corrections = {{"〈", "く"}, {"<", "く"}, {"＜", "く"}, {"L", "し"},
      |                                                      ^~~~
/home/user/builds/gazou/src/ocr.cpp:16:62: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   16 |     corrections = {{"〈", "く"}, {"<", "く"}, {"＜", "く"}, {"L", "し"},
      |                                                              ^~~
/home/user/builds/gazou/src/ocr.cpp:16:67: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   16 |     corrections = {{"〈", "く"}, {"<", "く"}, {"＜", "く"}, {"L", "し"},
      |                                                                   ^~~~
/home/user/builds/gazou/src/ocr.cpp:17:21: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   17 |                    {"Ｌ", "し"}, {"z", "え"}, {"Z", "え"},  {"U", "じ"},
      |                     ^~~~
/home/user/builds/gazou/src/ocr.cpp:17:27: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   17 |                    {"Ｌ", "し"}, {"z", "え"}, {"Z", "え"},  {"U", "じ"},
      |                           ^~~~
/home/user/builds/gazou/src/ocr.cpp:17:35: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   17 |                    {"Ｌ", "し"}, {"z", "え"}, {"Z", "え"},  {"U", "じ"},
      |                                   ^~~
/home/user/builds/gazou/src/ocr.cpp:17:40: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   17 |                    {"Ｌ", "し"}, {"z", "え"}, {"Z", "え"},  {"U", "じ"},
      |                                        ^~~~
/home/user/builds/gazou/src/ocr.cpp:17:48: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   17 |                    {"Ｌ", "し"}, {"z", "え"}, {"Z", "え"},  {"U", "じ"},
      |                                                ^~~
/home/user/builds/gazou/src/ocr.cpp:17:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   17 |                    {"Ｌ", "し"}, {"z", "え"}, {"Z", "え"},  {"U", "じ"},
      |                                                     ^~~~
/home/user/builds/gazou/src/ocr.cpp:17:62: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   17 |                    {"Ｌ", "し"}, {"z", "え"}, {"Z", "え"},  {"U", "じ"},
      |                                                              ^~~
/home/user/builds/gazou/src/ocr.cpp:17:67: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   17 |                    {"Ｌ", "し"}, {"z", "え"}, {"Z", "え"},  {"U", "じ"},
      |                                                                   ^~~~
/home/user/builds/gazou/src/ocr.cpp:18:21: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   18 |                    {"ー", ""},   {"一", " "}, {"―", ""},    {"‐", ""},
      |                     ^~~~
/home/user/builds/gazou/src/ocr.cpp:18:27: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   18 |                    {"ー", ""},   {"一", " "}, {"―", ""},    {"‐", ""},
      |                           ^~
/home/user/builds/gazou/src/ocr.cpp:18:35: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   18 |                    {"ー", ""},   {"一", " "}, {"―", ""},    {"‐", ""},
      |                                   ^~~~
/home/user/builds/gazou/src/ocr.cpp:18:41: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   18 |                    {"ー", ""},   {"一", " "}, {"―", ""},    {"‐", ""},
      |                                         ^~~
/home/user/builds/gazou/src/ocr.cpp:18:48: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   18 |                    {"ー", ""},   {"一", " "}, {"―", ""},    {"‐", ""},
      |                                                ^~~
/home/user/builds/gazou/src/ocr.cpp:18:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   18 |                    {"ー", ""},   {"一", " "}, {"―", ""},    {"‐", ""},
      |                                                     ^~
/home/user/builds/gazou/src/ocr.cpp:18:62: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   18 |                    {"ー", ""},   {"一", " "}, {"―", ""},    {"‐", ""},
      |                                                              ^~~
/home/user/builds/gazou/src/ocr.cpp:18:67: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   18 |                    {"ー", ""},   {"一", " "}, {"―", ""},    {"‐", ""},
      |                                                                   ^~
/home/user/builds/gazou/src/ocr.cpp:19:21: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   19 |                    {"—", ""},    {"－", ""},  {"-", ""},    {"_", ""},
      |                     ^~~
/home/user/builds/gazou/src/ocr.cpp:19:26: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   19 |                    {"—", ""},    {"－", ""},  {"-", ""},    {"_", ""},
      |                          ^~
/home/user/builds/gazou/src/ocr.cpp:19:35: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   19 |                    {"—", ""},    {"－", ""},  {"-", ""},    {"_", ""},
      |                                   ^~~~
/home/user/builds/gazou/src/ocr.cpp:19:41: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   19 |                    {"—", ""},    {"－", ""},  {"-", ""},    {"_", ""},
      |                                         ^~
/home/user/builds/gazou/src/ocr.cpp:19:48: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   19 |                    {"—", ""},    {"－", ""},  {"-", ""},    {"_", ""},
      |                                                ^~~
/home/user/builds/gazou/src/ocr.cpp:19:53: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   19 |                    {"—", ""},    {"－", ""},  {"-", ""},    {"_", ""},
      |                                                     ^~
/home/user/builds/gazou/src/ocr.cpp:19:62: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   19 |                    {"—", ""},    {"－", ""},  {"-", ""},    {"_", ""},
      |                                                              ^~~
/home/user/builds/gazou/src/ocr.cpp:19:67: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   19 |                    {"—", ""},    {"－", ""},  {"-", ""},    {"_", ""},
      |                                                                   ^~
/home/user/builds/gazou/src/ocr.cpp:20:21: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   20 |                    {"|", ""}};
      |                     ^~~
/home/user/builds/gazou/src/ocr.cpp:20:26: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   20 |                    {"|", ""}};
      |                          ^~
/home/user/builds/gazou/src/ocr.cpp: In member function ‘PIX* OCR::processImage(QString, bool)’:
/home/user/builds/gazou/src/ocr.cpp:75:55: error: invalid use of incomplete type ‘PIX’ {aka ‘struct Pix’}
   75 |     float pixelAvg = pixAverageOnLine(pixs, 0, 0, pixs->w - 1, 0, 1);
      |                                                       ^~
In file included from /usr/include/leptonica/alltypes.h:54,
                 from /usr/include/leptonica/allheaders.h:35,
                 from /home/user/builds/gazou/src/ocr.h:6,
                 from /home/user/builds/gazou/src/ocr.cpp:10:
/usr/include/leptonica/colorfill.h:49:12: note: forward declaration of ‘PIX’ {aka ‘struct Pix’}
   49 |     struct Pix     *pixs;        /*!< clone of source pix                    */
      |            ^~~
/home/user/builds/gazou/src/ocr.cpp:77:39: error: invalid use of incomplete type ‘PIX’ {aka ‘struct Pix’}
   77 |         pixAverageOnLine(pixs, 0, pixs->h - 1, pixs->w - 1, pixs->h - 1, 1);
      |                                       ^~
/usr/include/leptonica/colorfill.h:49:12: note: forward declaration of ‘PIX’ {aka ‘struct Pix’}
   49 |     struct Pix     *pixs;        /*!< clone of source pix                    */
      |            ^~~
/home/user/builds/gazou/src/ocr.cpp:77:52: error: invalid use of incomplete type ‘PIX’ {aka ‘struct Pix’}
   77 |         pixAverageOnLine(pixs, 0, pixs->h - 1, pixs->w - 1, pixs->h - 1, 1);
      |                                                    ^~
/usr/include/leptonica/colorfill.h:49:12: note: forward declaration of ‘PIX’ {aka ‘struct Pix’}
   49 |     struct Pix     *pixs;        /*!< clone of source pix                    */
      |            ^~~
/home/user/builds/gazou/src/ocr.cpp:77:65: error: invalid use of incomplete type ‘PIX’ {aka ‘struct Pix’}
   77 |         pixAverageOnLine(pixs, 0, pixs->h - 1, pixs->w - 1, pixs->h - 1, 1);
      |                                                                 ^~
/usr/include/leptonica/colorfill.h:49:12: note: forward declaration of ‘PIX’ {aka ‘struct Pix’}
   49 |     struct Pix     *pixs;        /*!< clone of source pix                    */
      |            ^~~
/home/user/builds/gazou/src/ocr.cpp:78:53: error: invalid use of incomplete type ‘PIX’ {aka ‘struct Pix’}
   78 |     pixelAvg += pixAverageOnLine(pixs, 0, 0, 0, pixs->h - 1, 1);
      |                                                     ^~
/usr/include/leptonica/colorfill.h:49:12: note: forward declaration of ‘PIX’ {aka ‘struct Pix’}
   49 |     struct Pix     *pixs;        /*!< clone of source pix                    */
      |            ^~~
/home/user/builds/gazou/src/ocr.cpp:80:36: error: invalid use of incomplete type ‘PIX’ {aka ‘struct Pix’}
   80 |         pixAverageOnLine(pixs, pixs->w - 1, 0, pixs->w - 1, pixs->h - 1, 1);
      |                                    ^~
/usr/include/leptonica/colorfill.h:49:12: note: forward declaration of ‘PIX’ {aka ‘struct Pix’}
   49 |     struct Pix     *pixs;        /*!< clone of source pix                    */
      |            ^~~
/home/user/builds/gazou/src/ocr.cpp:80:52: error: invalid use of incomplete type ‘PIX’ {aka ‘struct Pix’}
   80 |         pixAverageOnLine(pixs, pixs->w - 1, 0, pixs->w - 1, pixs->h - 1, 1);
      |                                                    ^~
/usr/include/leptonica/colorfill.h:49:12: note: forward declaration of ‘PIX’ {aka ‘struct Pix’}
   49 |     struct Pix     *pixs;        /*!< clone of source pix                    */
      |            ^~~
/home/user/builds/gazou/src/ocr.cpp:80:65: error: invalid use of incomplete type ‘PIX’ {aka ‘struct Pix’}
   80 |         pixAverageOnLine(pixs, pixs->w - 1, 0, pixs->w - 1, pixs->h - 1, 1);
      |                                                                 ^~
/usr/include/leptonica/colorfill.h:49:12: note: forward declaration of ‘PIX’ {aka ‘struct Pix’}
   49 |     struct Pix     *pixs;        /*!< clone of source pix                    */
      |            ^~~
/home/user/builds/gazou/src/ocr.cpp: In member function ‘void OCR::postprocess()’:
/home/user/builds/gazou/src/ocr.cpp:169:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  169 |         correctCommonMistake(curr, "く", prev, next);
      |                                    ^~~~
/home/user/builds/gazou/src/ocr.cpp:170:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  170 |         correctCommonMistake(curr, "し", prev, next);
      |                                    ^~~~
/home/user/builds/gazou/src/ocr.cpp:171:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  171 |         correctCommonMistake(curr, "じ", prev, next);
      |                                    ^~~~
/home/user/builds/gazou/src/ocr.cpp:172:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  172 |         correctCommonMistake(curr, "え", prev, next);
      |                                    ^~~~
/home/user/builds/gazou/src/ocr.cpp:173:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  173 |         correctCommonMistake(curr, "、", prev, next);
      |                                    ^~~~
/home/user/builds/gazou/src/ocr.cpp:174:36: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  174 |         correctCommonMistake(curr, "。", prev, next);
      |                                    ^~~~
make[2]: *** [CMakeFiles/gazou.dir/build.make:153: CMakeFiles/gazou.dir/src/ocr.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/gazou.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`
Upon looking deeper into this it seems to be an error with the current version of leptonica. I downgraded to version 1.82.02 (of leptonica) and it builds properly, but the .so file that gazou looiks for is no longer in that version so it exits with a file not found error.

# Steps to reproduce
On a fresh install of Arch Linux download the dependencies and clone the git repo.
Use cmake with DGUI either on or off.
run make

**Comment by Lisible** [comment]
Encountering the same issue here

**Comment by kamui-fin** [comment]
Apologies for the delay (was finals period), the AUR package is updated and should be fixed now.

**Comment by Fabian42** [comment]
Confirmed fixed!

(Unlike the GitHub website, which is blank for me in regular tabs, WTF…)
