### ISSUE TITLE
Fedora 38 uses tesseract 5.3 -- Gazou wants tessearct 5.2 --> after Update will not run

### ISSUE THREAD

**Issue by jaminW55** [kamui-fin/gazou#20]
gazou wants to use tessearct 5.2; but Fedora 38 has tesseract 5.3 - thus it will not work
Error Text: "gazou: error while loading shared libraries: libtesseract.so.5.2.0: cannot open shared object file: No such file or directory"
Error in Attachment.
![Screenshot_20230514_154633](https://github.com/kamui-fin/gazou/assets/133602605/f9b77f83-90cc-4faa-ac78-90480d3babc9)

**Comment by kamui-fin** [comment]
Could you try re-compiling again after removing `build/`? I think it just needs to be linked to the new updated version of libtesseract, so building it again should do the trick.

**Comment by jaminW55** [comment]
Hello. I just tried this and it ran into the same error.

**Comment by jaminW55** [comment]
Do you have any other recommendations, or should I try deleting what I have currently and reinstalling completely?

**Comment by nomonight** [comment]
I recently updated to Fedora 38 and encountered the same problem. I just re-did the steps from README under "Install" section and it fixed the problem. So yeah, re-compiling helps.
