### ISSUE TITLE
Problem Running CLI version in Script from Qtile WM (X not Wayland)

### ISSUE THREAD

**Issue by yuki-tsubaki** [kamui-fin/gazou#23]
### Context
I am trying to get an OCR setup that works even in programs that try to keep focus when you are using them which (which breaks the built in screenshot utility of gazou because it gets focus back from the gazou region select gui; this can be worked around by switching to another virtual desktop in my experience but I want it to be a bit smoother). To fix this I wanted to use gazou in a script where I use maim to take the screenshot (which is able to keep focus somehow) and then use gazou piped into `xclip -i -selection clipboard` to send the OCR results to the clipboard. The script works when run manually from my terminal emulator, but does not work when run from a keyboard shortcut in my window manager (Qtile).
### Errors
When running `gazou path/to/ocr.jpg > output` from a keyboard shortcut, output is empty. When adding stderr redirection the output file has the following contents:

```
Error in pixReadMem: data not defined
Error in pixGetDepth: pix not defined
Error in pixConvertRGBToGray: pixs not defined
Error in pixScale: pixs not defined
Error in pixUnsharpMaskingGray: pixs not defined
Error in pixOtsuAdaptiveThreshold: pixs not defined or not 8 bpp
Error in pixSelectBySize: pixs not defined
```   
I assume this is caused by it not being run from a normal graphical environment, but it is different from the error I get when running it directly from the tty, which is this:
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

Do you have any ideas on why this is happening, or ways I might get around it? Thanks in advance!

**Comment by kamui-fin** [comment]
Fixed in v0.3.1
