### ISSUE TITLE
No output option

### ISSUE THREAD

**Issue by DomBito** [kamui-fin/gazou#7]
The idea of the cli would be to use in shell scripts as you said, but there is no output option and I can't pipe the output text to something else.
When I try to pipe it to another command, say xargs, as I do with an echo command, it doesn't work and it happly displays the output text in the terminal instead.

**Comment by jaxter184** [comment]
It seems like gazou outputs text information to stderr instead of stdout for some reason. To get around this, you can use `gazou file.png &> output.txt`, or `gazou file.png 2> output.txt`.

**Comment by kamui-fin** [comment]
This is now fixed in the newest version (v0.2.0)
